### ISSUE TITLE
Cleanup handling of riding & goal properties

### ISSUE THREAD

**Issue by Arnuh** [Arnuh/EchoPet#129]
With phantom I decided on a method of configuring lots of ai/goal/brain stuff per pet type. Need to adapt current ones like follow & riding to use that system.

Initial example I made
```
riding:
  allow: true
  walkSpeed: xx
  flySpeed: xx
  jumpHeight: xx -- ? Might as well
  canFly: false
  hover: false
goal:
  walkSpeed: xx
  flySpeed: xx
  jumpHeight: xx
  follow:
    startDistance: 6
    stopDistance: 2
    teleportDistance: 10
    speedModifier: 1
brain:
  random stuff similar to goal but some extra fancy stuff
```
