### ISSUE TITLE
Rider pet values not loaded on login.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#70]
Reproduction:

- /pet bee bee
- Change the top bees and the bottom bees values to angry.
- Log out.
- Flatfile DB shows:

```
  231881e6-de0f-4224-bfce-0b78e07d862b:
    pet:
      type: BEE
      name: andrewkm's Bee
      data:
        angry: true
    rider:
      type: BEE
      name: andrewkm's Bee
      data:
        angry: true
```

- Log back in and get: https://i.imgur.com/Ju9HpFz.png
- Flatfile DB shows correctly however:

```
  231881e6-de0f-4224-bfce-0b78e07d862b:
    pet:
      type: BEE
      name: andrewkm's Bee
      data:
        angry: true
    rider:
      type: BEE
      name: andrewkm's Bee
      data:
        angry: true
```

Issue is somewhere on login when loading the rider pet's values from DB/Flatfile.
