### ISSUE TITLE
Someone named pet "?" and it blew up console on load.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#77]
Please prevent ? in names.
Blows shit up on startup.

```
  b0773db1-1ca3-44fc-9240-229d6e16a945:
    pet:
      type: SHEEP
      name: ?
      data:
        baby: true
        black: true
```

Boom: https://pastebin.com/raw/D67FXfEh
